### ISSUE TITLE
File not loading properly for very small number of cells

### ISSUE THREAD

**Issue by Pointillomic** [interactivereport/cellxgene_VIP#103]
Hello, 

I seem to be having an issue with opening h5ad files that have a small number of cells recorded - when I subset working h5ad files to 9 cells, the file does not load properly in cellxgene VIP, while it does in regular cellxgene. 100 cells work in VIP, whereas down to 1 cell seems to work for regular cellxgene.

There are some differences in cellxgene versions used (cellxgene v1.0.1 for regular cellxgene and cellxgene v1.1.1 for VIP)

I've attached the screenshot of what I see as I don't know where to find proper error messages:
<img width="1094" alt="Screenshot 2024-02-01 at 2 54 02 PM" src="https://github.com/interactivereport/cellxgene_VIP/assets/122571920/e1b06db0-6b58-488c-b47e-7483e4418292">

Any help with this would be greatly appreciated!

**Comment by z5ouyang** [comment]
Interesting... I cannot reproduce it on the [demo site](https://cellxgenevip-ms.bxgenomics.com/) .
![image](https://github.com/interactivereport/cellxgene_VIP/assets/30639029/f902fc97-0c05-4ca9-8af9-e232fcd34326)
