### ISSUE TITLE
Install cellxgene_VIP on Windows

### ISSUE THREAD

**Issue by Seawestking** [interactivereport/cellxgene_VIP#108]
Hi, I need help, plz.
When I'm trying to install cellxgene_VIP on windows, it seems no tutorial on this. (only linux or MacOS platform)
Does cellxgene_VIP not support Windows platform?
If so, is it necessary for me to install it on linux server?
Could you please help me to fix it? I'm appreciating that!

**Comment by z5ouyang** [comment]
Sorry for the delay, we don't support Windows.
But it is possible to install it on Windows as long as you can set up a conda env, and manually run the commands from ```install_VIPlight.sh``` accordingly on windows.
Hope this helps.
