### ISSUE TITLE
Violin plot error : missing value 

### ISSUE THREAD

**Issue by aniseedDB** [interactivereport/cellxgene_VIP#109]
Hi everyone, 
there seems to be an issue with Violin plot > Single Gene/Multi-factors (cf. image below)
![violin-multi](https://github.com/interactivereport/cellxgene_VIP/assets/151924486/efef3dbf-5799-4bd9-8566-ce5adbcb1744)
Any ideas?

**Comment by z5ouyang** [comment]
Thanks for reporting! It is not the code (Thankfully), but the server instance cliche.
