### ISSUE TITLE
Plotting layout overlaps in VIP demo

### ISSUE THREAD

**Issue by LuckyMD** [interactivereport/cellxgene_VIP#20]
Hi,

This looks like a really nice addition to cellxgene! I however noticed that the plots overlap a little when just highlighting microglia and phagocytes as two groups, inputting CD3E and CD4 as genes and then looking at the stacked violin plot.

Image of plots overlapping with axis labels:
<img width="517" alt="Screenshot 2020-09-01 at 10 14 31" src="https://user-images.githubusercontent.com/13019956/91825148-2586b700-ec3c-11ea-9e6c-02b6a3969e21.png">

Session file:
[cellxgene.ms_nature_2019_rowitch_filtered_normalized_log1p_non_scaled_with_embedings_and_labels.info.txt](https://github.com/interactivereport/cellxgene_VIP/files/5154792/cellxgene.ms_nature_2019_rowitch_filtered_normalized_log1p_non_scaled_with_embedings_and_labels.info.txt)

**Comment by interactivereport** [comment]
Please change the font size to 11 in "Figure Option" to avoid overlapping. I will set the default to 11.

<img width="453" alt="Screen Shot 2020-09-01 at 9 25 03 AM" src="https://user-images.githubusercontent.com/29576524/91856999-4bf52400-ec35-11ea-8416-3c9b08ba284a.png">

![download](https://user-images.githubusercontent.com/29576524/91857017-50214180-ec35-11ea-8eb3-d1312ed04090.png)
