### ISSUE TITLE
Hosting cellxgene_VIP with Heroku

### ISSUE THREAD

**Issue by phoebee-h** [interactivereport/cellxgene_VIP#22]
Hi,
Thanks for the nice work, which makes it much easier to visualize the result with so many flexible functions.
I've hosted the cellxgene result successfully with Heroku, but I don't know what to do with your plugin version. What should be modified in the [Dockerfile mentioned in cellxgene github](https://github.com/chanzuckerberg/cellxgene/blob/main/Dockerfile)?

I've tried to replace `pip3 install cellxgene` with git clone, but it does not work though...

```
FROM ubuntu:bionic

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && \
    apt-get install -y build-essential libxml2-dev python3-dev python3-pip zlib1g-dev python3-requests python3-aiohttp && \
    python3 -m pip install --upgrade pip && \
    # pip3 install cellxgene
    apt-get install -y git &&\
    git clone https://github.com/interactivereport/cellxgene_VIP.git 
```

Forgive me if this question is not so directly to your package development.

Thank you.

**Comment by interactivereport** [comment]
Could you please follow the installation instruction?

https://github.com/interactivereport/cellxgene_VIP#installation-instruction

You need to run "**config.sh**" to generate and copy files needed by cellxgene_VIP.
