### ISSUE TITLE
cellxgene_VIP installation error

### ISSUE THREAD

**Issue by wariobrega** [interactivereport/cellxgene_VIP#24]
Hello, and first of all congratulations for your tool, it seems very useful and I'd like to propose it in our scSeq  visualization and Analysis workflow in my laboratory.

I am writing you because I have troubles installing the tool on my workstation and I can't figure out why. 
I followed the instruction you put on the website, namely:

1) create an empty python 3.7 conda environment
2) clone your git repo
3) run config.sh (not as root of course)

the config.sh gives a series of errors in the installations. I attache the whole log in this thread because the list of errors in without any doubt very long and I'm scratching my head trying to figure out what's working and whatnot.

Hope you can help me out on this. 

Cheers,

Daniele
[cellxgene_VIP_install.log](https://github.com/interactivereport/cellxgene_VIP/files/5232867/cellxgene_VIP_install.log)

**Comment by interactivereport** [comment]
We improved "config.sh". Could you please pull the latest version and run "config.sh"?

I also noticed these in the log,
```
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
```
Please make sure you have enough disk space to install it.

**Comment by wariobrega** [comment]
Hi @interactivereport  I tried to re-install it and yes, I definitely get a full disk error, although it seems to me that the disks are not full (I have 838GB free on `/` ).  and more than 20TB free inside the disk in shich I-m trying to install cellxgene_VIP.

sorry about the naive question but is it possible that the config is installing all its requirements in other locations?

**Comment by wariobrega** [comment]
A quick update:

I started running each of the command in the config.sh separately, and apparently the error seems to be at line 119 (`make pydist`)

I am attaching you the screenshot of the error, maybe there is a file corruption problem? 

![image](https://user-images.githubusercontent.com/10073781/93598817-898bd800-f9bd-11ea-9cae-ce8d4d0462ef.png)

all best,

Daniele

**Comment by wariobrega** [comment]
Hello, 

just a quick update:

I redownloaded the last cellxgene VIP, dockerize it and it seems that the installation worked now. I think it was something not working between my workstation and the old config.sh.
