### ISSUE TITLE
error loading cellxgene

### ISSUE THREAD

**Issue by longfeili5170** [interactivereport/cellxgene_VIP#27]
Hi all,

Thanks for developing such an excellent plugin.But I have some problems with its use.

When I try to run through cellxgene's example data(pbmc3k.h5ad), it works well.But when I use my own data or modify pbmc3k.h5ad by scanpy, some errors will appear.I noticed that there can be no null values in categorical annotation.And I can run the data normally by installing cellxgene separately.
Here is the error message and web page information：
<img width="910" alt="Screen Shot 2020-12-20 at 4 52 42 PM" src="https://user-images.githubusercontent.com/68364890/102709899-87e9ed00-42e9-11eb-8d45-032a0f2c2504.png">
<img width="1042" alt="Screen Shot 2020-12-20 at 4 14 36 PM" src="https://user-images.githubusercontent.com/68364890/102709903-8b7d7400-42e9-11eb-9ca6-23cc18aee07f.png">

How should I start troubleshooting? I have no idea what the problem is.

Thanks!

Li

**Comment by longfeili5170** [comment]
I found that this problem is caused by the convert function of cellxgene. For some h5ad files of 0.16.4 version, cellxgene cannot convert cxg files. Linking to https://github.com/chanzuckerberg/cellxgene/issues/1797.
When I upgraded cellxgene to 0.16.6, the problem disappeared. I can open the cellxgene interface, but the vip button disappears.
Any suggestions on how to upgrade cellxgene while keeping the vip button?
Thank you!

**Comment by z5ouyang** [comment]
Thank you for report this bug. We are still working on upgrade VIP with cellxgene. Since there are a few core changes in cellxgene, the current VIP is not compatible with new cellxgene.
If you can change the 'None' in h5ad into empty string or string 'None', the old version should work.
