### ISSUE TITLE
I got NA for  all options

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#28]
Hi,
VIP works fine, but then did not work, do not why.
![image](https://user-images.githubusercontent.com/23288387/104487179-c302d780-559a-11eb-9c94-e8bc16c81fcb.png)

**Comment by interactivereport** [comment]
Did you follow the installation from step 1 to 3? Did you notice the message in Chrome console similar to step 4? Any error messages from server side console?

Could you please test the demo site to check if it works in your Chrome browser?

**Comment by FADHLyemen** [comment]
I got this in chrome
![image](https://user-images.githubusercontent.com/23288387/104546906-33414580-55fb-11eb-872f-6d9e1ba05ef3.png)

**Comment by FADHLyemen** [comment]
cellxgeneVIP works with some port and not other port. I do not know why?

**Comment by z5ouyang** [comment]
Please ignore the db file which is used for other purposes. And the usable port depends on your system, please consult with your system admin.

I will close the issue, please feel free to reopen if the issue persists.
