### ISSUE TITLE
bug in Group Violin, 2D density and Gene Detected

### ISSUE THREAD

**Issue by longfeili5170** [interactivereport/cellxgene_VIP#30]
Hi all,

Thanks for developing such an excellent plugin.I can use all functions smoothly, except for the following three:
When I use Group Violin and 2D density, it will run in the background, but they do not return the correct picture：
<img width="735" alt="屏幕快照 2021-01-20 下午8 02 41" src="https://user-images.githubusercontent.com/68364890/105178004-73a44480-5b62-11eb-9459-e64e7153a1f0.png">
<img width="741" alt="屏幕快照 2021-01-20 下午8 15 09" src="https://user-images.githubusercontent.com/68364890/105178009-74d57180-5b62-11eb-89fe-4088adcde9ab.png">

When I use Gene Detected, it report errors like this:
<img width="739" alt="屏幕快照 2021-01-20 下午8 16 39" src="https://user-images.githubusercontent.com/68364890/105178180-abab8780-5b62-11eb-99ce-0ea7ef3d1fb3.png">

What might these errors be related to？
Thanks!

Li

**Comment by interactivereport** [comment]
It is related to R and R packages. I installed these packages to system default R as root. We are working on a local installation without root privilege.

bubbleMap.R:require(tidyverse)
bubbleMap.R:require(ggpubr)
Density2D.R:if(!require(ggplot2,quietly=T) || !require(MASS,quietly=T) || !require(dplyr,quietly=T,warn.conflicts=F)) stop("ggplot2, dplyr and MASS are required R package!")
violin.R:  require(ggplot2)
violin.R:  require(dplyr)
violin.R:  require(RColorBrewer)
violin.R:  require(glue)
violin.R:  require(ggpubr)
violin.R:  require(gridExtra)
(test2) [bzhang1@omicsoft01 cellxgene_VIP]$ grep library *.R
volcano.R:library(ggplot2)
volcano.R:library(ggrepel)
volcano.R:library(ggrastr)

**Comment by longfeili5170** [comment]
Thank you for your reply.
I installed the relevant R package, and then Group Violin, 2D density can run normally.
But Gene Detected still gets the same error.

**Comment by interactivereport** [comment]
Fixed the bug. Please pull the latest code and then run "./update.VIPInterface.sh"

**Comment by longfeili5170** [comment]
It works, thanks for your reply！
