### ISSUE TITLE
Error: The port selected is in use, please configure an open port.

### ISSUE THREAD

**Issue by dfermin** [interactivereport/cellxgene_VIP#31]
Hello.
I've been able to install cellxgene_VIP but the visualization plugin window is "blank".
When I restart the program I now get a new error:

```
Error: The port selected 5005 is in use, please configure an open port.
```

I've tried restarting it with multiple ports 5005 to 5100 and I get the same message with all of them. 

Any suggestions what might be going on?
Thanks

**Comment by dfermin** [comment]
Okay I've got an update. If I wait about 5 minutes the command works. I'm not sure why.
However although the page loads the visualization plugin window is now missing.

I looked at the chrome developer tools console and I get this text:
```
Form submission canceled because the form is not connected (index):1
```

**Comment by likejie** [comment]
Hi,
Would you please confirm your ports 5005 to 5100 are open or used by another program? Usually when other program is using your specified port, it would complain. Also, when you stop a cellxgene launch, wait a little bit for it to release the port and then start again (point to the same port).
Hope this helps.

**Comment by z5ouyang** [comment]
@dfermin could you please download and re-install the current version of vip, run './config.sh' in your env since you have your env setup. And please let us know if you are still having issues.

Best,
