### ISSUE TITLE
pandas error when create new label 

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#32]
Hi,
I created a new category and got the below error when use that variable for grouping in the violin  and other plots. other category variables did not have error. Could you help?

`ERROR @server: Traceback (most recent call last):
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['test'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
`

**Comment by likejie** [comment]
Hi,
I think this is related to your new category contains nans.
This might help you, please try it out.
https://github.com/interactivereport/cellxgene_VIP/issues/25#issuecomment-701541703
Thanks!

**Comment by FADHLyemen** [comment]
I tried but did not work,
The reason in my case is the unassigned cells. the levels of test should be only two not three. Any suggestions?
![image](https://user-images.githubusercontent.com/23288387/106042856-9b883080-60ab-11eb-8a82-df3d268af7a3.png)

**Comment by likejie** [comment]
It would be helpful to get more details on how you created the new category annotation. Did you use the manual annotation mode from cellxgene? Wondering why there is 0 unassigned cell. Might need to remove unassigned from the meta data.

**Comment by FADHLyemen** [comment]
Yes, it is the manual annotation from cellxgene using 'create new category'
There is no way you can remove unassigned from the category, it is a default in cellxgene.

**Comment by z5ouyang** [comment]
Currently the VIP didn't support the custom annotation yet.

**Comment by rgranit** [comment]
@z5ouyang any plans to add the option of plotting with custom annotations? I believe it's very useful

**Comment by z5ouyang** [comment]
@rgranit It is on our to do list. it is a little tricky to obtain those information from cellxgene. Meanwhile, If your custom annotations are related to the annotations in h5ad, you can explore "combinatorial annotation" and/or "abbreviations of annotations".

**Comment by z5ouyang** [comment]
@rgranit @FADHLyemen custom annotations are enabled in VIP.
