### ISSUE TITLE
The server situation required to deploy cellxgene-vip

### ISSUE THREAD

**Issue by longfeili5170** [interactivereport/cellxgene_VIP#34]
Hello!
I plan to deploy cellxgene to the server, but I don't know the required server situation.
For example, when I plan to deploy 5 data sets of 100k cells, what is the server situation I need, such as running memory?

Thanks！

**Comment by z5ouyang** [comment]
Normally the memory usage is the same as the h5ad file, if you host a dataset at a port. So total memory of your 5 datasets is similar to the total of five h5ad files on disk.
