### ISSUE TITLE
Method Not Allowed error when trying to plot data through VIP 

### ISSUE THREAD

**Issue by ShanSabri** [interactivereport/cellxgene_VIP#35]
When launching VIP using `/home/ubuntu/.Anaconda3/envs/VIP/bin/cellxgene launch test.h5ad --annotations-file ~/cellxgene/annotation_collection.csv --max-category-items 50 --port 3839 --host 0.0.0.0 --open` I get an error when trying to plot violins, heatmap, UMAP, etc: 

```
405<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Screenshot: 
![image](https://user-images.githubusercontent.com/4357318/107817502-1b103380-6d2b-11eb-9c18-5c16253e547c.png)

Any ideas?

**Comment by z5ouyang** [comment]
Is the annotation CP and DN are annotation from the custom annotation csv? Currently the VIP does not support custom annotation out of h5ad files. We are working on getting the custom annotation information from cellxgene.

**Comment by ShanSabri** [comment]
These are annotations within `anndata.obs` and we not supplied via a custom annotation csv.

**Comment by z5ouyang** [comment]
Then do you mind to obtain the lated VIP, and run ./config.sh to update to the newest version. I think it might related to the change we did for obtaining the data. Please let us know if the error persists.

**Comment by ShanSabri** [comment]
Sure thing: 
```
conda activate VIP
cd cellxgene_VIP
git pull origin master
./config.sh
```

Build is successful: 
```
...
...
Successfully built cellxgene
Installing collected packages: cellxgene
Successfully installed cellxgene-0.16.7
```

Looks like it worked! 
![image](https://user-images.githubusercontent.com/4357318/109058046-5f8ac000-7697-11eb-8fb8-7ebb9dbe2197.png)
