### ISSUE TITLE
can you add spilt by and group by to dot plot ?

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#36]
HI,
How to add split by and group by in the dot plot?

**Comment by z5ouyang** [comment]
Could you please elaborate a little bit more? and use cases? thanks

**Comment by FADHLyemen** [comment]
Just, in DotPlot function in Seurat we can use group.by and split.by. In VIP we have only split.by. in Group violin plot in VIP, we have group by and also split by but this is not available in dot plot.

**Comment by z5ouyang** [comment]
The meaning of 'split' in VIP is different from Seurat. The 'Group by' in 'Dot Plot' of VIP archives the 'split' function from the Seurat. As the attached example, where the y-axis 'split' by cell types. If this is not what you plan to have. Could you please have an example image to show what's your goal is? Thanks.
![download](https://user-images.githubusercontent.com/30639029/109078660-90c4b980-76b2-11eb-9025-a52014bafa07.png)

**Comment by FADHLyemen** [comment]
Good example, so how to plot the above dot plot in different disease type? so you will get B cells in case and another row for B cells for the control.

**Comment by interactivereport** [comment]
Please check page 32 of the preprint. First, you need to generate combo-annotation, 

<img width="400" alt="Screen Shot 2021-02-24 at 11 15 26 PM" src="https://user-images.githubusercontent.com/29576524/109102548-1ec29380-76f7-11eb-99c2-cf072ca2159b.png">


And then select "Custome_combine" group in Dot Plot,

<img width="400" alt="Screen Shot 2021-02-24 at 11 17 22 PM" src="https://user-images.githubusercontent.com/29576524/109102566-26823800-76f7-11eb-8b95-a69a3464fbcd.png">

Note: No B cells are found in controls.

**Comment by FADHLyemen** [comment]
Perfect, thank you

**Comment by FADHLyemen** [comment]
the order of the rows are based on alphabetic. Is there a way to show cellType in case first then same cellType in control?
I don' want something like
![image](https://user-images.githubusercontent.com/23288387/109962702-83fb2380-7cb9-11eb-9b3c-59889bcd6ec6.png)
I want AKIcontrol:Bcells  then COVID:Bcells.

**Comment by likejie** [comment]
What i can think for your case is that, if you want AKIcontrol:Bcells; COVID:Bcells only, you can select Bcells ONLY in cell type on the left side main category. It would give you what you want. But this would not list all combinations (disease and celltype) for you. You will need to do it one-by-one.

> the order of the rows are based on alphabetic. Is there a way to show cellType in case first then same cellType in control?
> I don' want something like
> ![image](https://user-images.githubusercontent.com/23288387/109962702-83fb2380-7cb9-11eb-9b3c-59889bcd6ec6.png)
> I want AKIcontrol:Bcells then COVID:Bcells.

**Comment by FADHLyemen** [comment]
But I need for all cellTypes.

**Comment by z5ouyang** [comment]
@FADHLyemen. Now the VIP is enabled for user cell annotations, so that you can name the selected cell group as you wanted. This enable you to be able to plot what you wanted.

**Comment by baohongz** [comment]
@FADHLyemen, now you can order labels freely after creating combo annotation.

<img width="541" alt="Screen Shot 2021-03-19 at 8 29 18 AM" src="https://user-images.githubusercontent.com/15882624/111780277-8d75b580-888d-11eb-9f5b-3d312e0c0fb7.png">
