### ISSUE TITLE
DEG in VIP get different list of genes from FindMarkers function

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#37]
When I choose Welch's t-test(diffxpy) from VIP DEG, I got different list of genes when I run the below line in R:

```
 FindMarkers(pima_scrna, ident.1 = "DKD", ident.2 = "LD",group.by='sampletype', min.pct = 0.5,
                               test.use='t')
```

the logfc from VIP looks weird something like 1071.22 which is very big.

**Comment by z5ouyang** [comment]
Please refer to https://github.com/theislab/diffxpy
thanks

**Comment by FADHLyemen** [comment]
I am not talking about diffxpy. I am talking about Welch's t test.
