### ISSUE TITLE
Wilcoxon rank sum (diffxpy) takes inf time

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#38]
could you check Wilcoxon rank sum (diffxpy) in DEF, I tried in different dataset and it takes inf time without returning any results.
Thank you

**Comment by FADHLyemen** [comment]
I tried also https://cellxgenevip-ms.bxgenomics.com/
it did not work

**Comment by z5ouyang** [comment]
The computational cost for Wilcoxon and Wald is very high. Please select less cells to start with if you intent to use those two methods. I tested with 58 and 105 cells, and the run was successfully but took a long time.
Meanwhile I did a little modification on the diffxpy implementation which I am not sure it matters. You can pull the latest code and update.VIP... in your python env.
![image](https://user-images.githubusercontent.com/30639029/110050477-cd269400-7d08-11eb-8549-0fc6fc98c774.png)
