### ISSUE TITLE
Discrepancy in expression values between VIP and CellXGene

### ISSUE THREAD

**Issue by ShanSabri** [interactivereport/cellxgene_VIP#41]
Hi, I'm noticing that the expression range seems to differ between CellXGene and the VIP plugin. 

In the example dataset (https://cellxgenevip-ms.bxgenomics.com) it looks like CD79A has a max normalized expression of 7.485:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/4357318/112528286-f53a6d80-8d71-11eb-86d4-64b7eb07a69f.png">

But when I plot the distribution of this gene across clusters I see that the y-axis is capped at 20: 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/4357318/112528425-20bd5800-8d72-11eb-93d3-1a0d7bcccea2.png">

How is this 20 computed? Also what does the `Expression cutoff:` field correspond to? How can I get these values on the same scale?

**Comment by interactivereport** [comment]
Please change "Scale data ... ..." option to "No".

<img width="400" alt="Screen Shot 2021-03-25 at 3 33 48 PM" src="https://user-images.githubusercontent.com/29576524/112533037-e8247b00-8d7f-11eb-82c6-44c8f3cc3327.png">

**Comment by ShanSabri** [comment]
Perfect - thank you!
