### ISSUE TITLE
unable to start device PNG

### ISSUE THREAD

**Issue by dfermin** [interactivereport/cellxgene_VIP#43]
I just downloaded the latest version from GitHub. 
I get the error message for DEG: `unable to start device PNG.`

I was able to fix this by adding:
`
options(bitmapType='cairo'); 
`

To the beginning of the `volcano.R` script.

Not sure if this is a "hack" or not but I thought you should be made aware.

**Comment by z5ouyang** [comment]
Thanks for the report with the solution. 

@baohongz, should we add this for all R plotting functions, since it seems caused by no X11 graphic support. And I don't have a device without X11 to reproduce this.

**Comment by dfermin** [comment]
Can’t hurt. You require the Cairo package so it would make sense in this case. 

Sent from my PDA. 
Please excuse typos & brevity.

**Comment by z5ouyang** [comment]
Updated the master
