### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by skim245** [interactivereport/cellxgene_VIP#44]
I'm having an issue installing cellxgene_VIP at  config.sh step 

/config.sh

Cloning into 'cellxgene'...
remote: Enumerating objects: 15941, done.
remote: Counting objects: 100% (640/640), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 15941 (delta 295), reused 461 (delta 231), pack-reused 15301
Receiving objects: 100% (15941/15941), 202.22 MiB | 6.54 MiB/s, done.
Resolving deltas: 100% (11203/11203), done.
Note: switching to 'bedbc87ed6178cd00a586feac3e99d4912d1c74e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at bedbc87 Release 0.16.7
sed: 1: "server/requirements.txt": bad flag in substitute command: 'q'
sed: 1: "server/requirements.txt": bad flag in substitute command: 'q'
sed: 1: "cellxgene/client/index_ ...": command c expects \ followed by text
sed: 1: "cellxgene/client/src/co ...": command c expects \ followed by text
sed: 1: "cellxgene/client/src/co ...": command c expects \ followed by text
sed: 1: "cellxgene/client/src/ut ...": command c expects \ followed by text
rm -rf build/ client/build build dist cellxgene.egg-info
cd server && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
rm -f common/web/templates/index.html
rm -rf common/web/static
rm -f common/web/csp-hashes.json
cd client && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
rm -rf node_modules
rm -f __tests__/screenshots/*.png
cd client && /Applications/Xcode.app/Contents/Developer/usr/bin/make ci build
npm ci
/bin/bash: npm: command not found
make[1]: *** [ci] Error 127
make: *** [build-client] Error 2
pip uninstall -y cellxgene || :
WARNING: Skipping cellxgene as it is not installed.
pip install dist/cellxgene*.tar.gz
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Users/miniconda3/envs/VIP/include/python3.8/UNKNOWN
sysconfig: /Users/miniconda3/envs/VIP/include/python3.8
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Requirement 'dist/cellxgene*.tar.gz' looks like a filename, but the file does not exist
Processing ./dist/cellxgene*.tar.gz
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/cellxgene_VIP-master/cellxgene/dist/cellxgene*.tar.gz'

make: *** [install-dist] Error 1
cp: /Users/miniconda3/envs/VIP/lib/python3.8/site-packages/server/common/web/static/.: No such file or directory
sed: 1: "/Users/minico ...": bad flag in substitute command: 'n'

ls -l /Users/miniconda3/envs/VIP/lib/python3.8/site-packages/server/common/web/static/.

ls: /Users/miniconda3/envs/VIP/lib/python3.8/site-packages/server/common/web/static/.: No such file or directory

thanks !

**Comment by z5ouyang** [comment]
It seems like the nodejs is not successfully installed. Can you check the following after activating the conda env:
```pip show nodejs```

If no records, please do install by: ```conda install nodejs=13.13.0```, if error, please report the error.

**Comment by skim245** [comment]
found no nodejs installed and getting below error. i'm currently on conda version 4.10.1


Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - nodejs=13.13.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by z5ouyang** [comment]
please try:
```conda install -c conda-forge nodejs=13.13.0```

**Comment by skim245** [comment]
@z5ouyang your suggestion worked for me ! but I still don't see VIP button does not appear after the install

**Comment by skim245** [comment]
i've run the config.sh again and now it was installed successfully and still no VIP button, 

and run the code above and here is the result 

assets							main-1781761257e368c0f01e.js.LICENSE.txt		obsolete-7ff3b9bcfba2dba2dca7c99b814ce63f.js
interface.html						main-1781761257e368c0f01e.js.map			obsolete-7ff3b9bcfba2dba2dca7c99b814ce63f.js.map
main-1781761257e368c0f01e.js				main-1a225c211b66b9e3647f.css
(VIP) MacBook-Pro:cellxgene_VIP $ 
(VIP) MacBook-Pro:cellxgene_VIP $ @skim245
-bash: @skim245: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ 
(VIP) MacBook-Pro:cellxgene_VIP$  
(VIP) MacBook-Pro:cellxgene_VIP$  
(VIP) MacBook-Pro:cellxgene_VIP$ ▲
-bash: ▲: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Leave a comment
usage: leave [[+]hhmm]
(VIP) MacBook-Pro:cellxgene_VIP$ No file chosen
-bash: No: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Attach files by dragging & dropping, selecting or pasting them.
[1] 26008
-bash: Attach: command not found
-bash: dropping,: command not found
[1]+  Exit 127                Attach files by dragging
(VIP) MacBook-Pro:cellxgene_VIP$ Remember, contributions to this repository should follow our GitHub Community Guidelines.
-bash: Remember,: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Assignees
-bash: Assignees: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ No one assigned
-bash: No: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Labels
-bash: Labels: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ None yet
-bash: None: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Projects
-bash: Projects: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ None yet
-bash: None: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Milestone
-bash: Milestone: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ No milestone
-bash: No: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Linked pull requests
-bash: Linked: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Successfully merging a pull request may close this issue.
-bash: Successfully: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ 
(VIP) MacBook-Pro:cellxgene_VIP$ None yet
-bash: None: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Notifications
-bash: Notifications: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ Customize
-bash: Customize: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ You’re receiving notifications because you authored the thread.
-bash: You’re: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ 2 participants
-bash: 2: command not found
(VIP)MacBook-Pro:cellxgene_VIP$ @z5ouyang
-bash: @z5ouyang: command not found
(VIP) MacBook-Pro:cellxgene_VIP$ @skim245

**Comment by z5ouyang** [comment]
Only the top information is needed, seems like you have installed correctly.
Did you cleared the browser cache?
Can you share the message in browser console:
1. click 'inspect' after right click on the chrome browser page;
2. check 'Disable cache' on the 'Network' tab in the inspect window;
3. click the console page, and refresh the cellxgene VIP page;
4. copy the information from the console.

**Comment by skim245** [comment]
I followed your suggestion and my console is empty, even after refreshing the cellxgene VIP page

**Comment by z5ouyang** [comment]
emmm, could you please share the results after the following command line in your activated env:
```strPath="$(python -c 'import site; print(site.getsitepackages()[0])')";ls -all $strPath/server/app/.```

**Comment by skim245** [comment]
Here is the results after running the command line 

total 216
drwxr-xr-x  13 User  staff    416 Apr 30 23:28 .
drwxr-xr-x  18 User staff    576 Apr 30 23:28 ..
-rwxr-xr-x@  1 User  staff   2661 Apr 30 23:28 Density2D.R
-rw-r--r--@  1 User staff  55287 Apr 30 23:28 VIPInterface.py
-rw-r--r--   1 User  staff      0 Apr 30 23:28 __init__.py
drwxr-xr-x   6 User  staff    192 Apr 30 23:28 __pycache__
-rw-r--r--   1 User  staff  16911 Apr 30 23:28 app.py
-rwxr-xr-x@  1 User  staff   4140 Apr 30 23:28 bubbleMap.R
-rw-r--r--   1 User staff   1047 Apr 30 23:28 decode_fbs.py
-rwxr-xr-x@  1 User  staff   2036 Apr 30 23:28 fgsea.R
drwxr-xr-x   4 User staff    128 Apr 25 08:46 gsea
-rwxr-xr-x@  1 User  staff   7537 Apr 30 23:28 violin.R
-rwxr-xr-x@  1 User  staff   2956 Apr 30 23:28 volcano.R

**Comment by z5ouyang** [comment]
The mac installation configuration is updated.
Please 
1. Pull the latest VIP;
2. Remove your current conda env;
2. Create a new conda env for VIP by using 'VIP.macOS.yml';
3. Install xcode for mac by command: ```xcode-select --install``` if you haven't install xcode;
4. Install VIP by ```./config.macOS.sh``` in the root folder.

Please feel free to reopen if installation is unsuccessful.
Thanks for the patience and using VIP!

**Comment by jackbrougher** [comment]
I'm having a follow up issue from this point. I was stuck at the same point as above on a mac install, but that worked for me.

Now I'm having issues with the "Rscript -e 'reticulate::py_config()'" line. After entering it, I receive the following error:

Error in python_config(python_version, required_module, forced = "RETICULATE_PYTHON") : 
  Error 126 occurred running /Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/config/config.py 
Calls: <Anonymous> ... initialize_python -> py_discover_config -> python_config
In addition: Warning message:
In system2(command = python, args = shQuote(config_script), stdout = TRUE,  :
  running command ''/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/config/config.py' '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/config/config.py' 2>/dev/null' had status 126
Execution halted


I see the next line, about specifying my python config in my VIP env. But, (and I may be dumb) I can't find a py_config in the VIP env?

**Comment by theDierickxLab** [comment]
./config.macOS.sh could not work for me still.

**Comment by z5ouyang** [comment]
@theDierickxLab please open a new issue, since this is closed, and might not related to your situation.
Please also provide more details, like your macOS version. You use the conda R or your system R etc. It would be difficult to help with just "not work".
Thanks!
