### ISSUE TITLE
ValueError: Less than 10 cells in a group!

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#46]
My cell numbers is each group are more than 10 cells and I still get the error 
ERROR @server: Traceback (most recent call last):
ValueError: Less than 10 cells in a group!

**Comment by z5ouyang** [comment]
thanks for reporting, from which plotting function?

**Comment by FADHLyemen** [comment]
there is no any combined groups
![image](https://user-images.githubusercontent.com/23288387/117582665-20cea880-b0d1-11eb-948a-df7e353a5814.png)

**Comment by z5ouyang** [comment]
I cannot reproduce this on our datasets, I assume you cannot share the data. Thus, could you please check a few things on the browser console (chrome: right click anywhere on the page, select 'inspect', select 'console' tab on the new opened side window).
1. DEGselCells()[1].length
2. Object.keys(getCells(null,true))
3. getCells(null,true)["celllist1"].length
4. getCells(null,true)["celllist2"].length

Thank you!

**Comment by FADHLyemen** [comment]
1- 0
2-Uncaught ReferenceError: getCells is not defined
    at <anonymous>:1:8
3-VM429:1 Uncaught ReferenceError: getCells is not defined
    at <anonymous>:1:1
4- Uncaught ReferenceError: getCells is not defined
    at <anonymous>:1:1

**Comment by z5ouyang** [comment]
Something is not correct, maybe you want to pull the latest version, or reinstall. you can test on our example instance: https://cellxgenevip-ms.bxgenomics.com/

If only one cell group was select on the cellxgene main window
> Object.keys(getCells(null,true))
["celllist1"]0: "celllist1"
If two groups
> Object.keys(getCells(null,true))
(2) ["celllist1", "celllist2"]

**Comment by z5ouyang** [comment]
If the latest version didn't fix this, please feel free to reopen the issue.

Thanks.
