### ISSUE TITLE
Seurat4 SeuratDisk exported h5ad cause blank VIP menu

### ISSUE THREAD

**Issue by likejie** [interactivereport/cellxgene_VIP#48]
If we are using Seurat v4 and SeuratDisk to export h5ad file, it seems that cellxgene basic still works fine but cellxgene VIP came up as blank.

```
library(Seurat)
library(SeuratDisk)
SaveH5Seurat(query, filename = "data.h5Seurat")
Convert("data.h5Seurat", dest = "h5ad")
```

**Comment by likejie** [comment]
Searched around and found the problem is SeuratDisk output h5ad file, and when read in by scanpy, this:
 
`adata.__dict__['_raw'].__dict__['_var']
` 
has a column named _index. But python has it reserved.
 
One solution is to rename `_index` to something else such as `features`:
 
`adata.__dict__['_raw'].__dict__['_var'] = adata.__dict__['_raw'].__dict__['_var'].rename(columns={'_index': 'features'})`

**Comment by z5ouyang** [comment]
If cellxgene works, VIP should work as well, since VIP didn't use scanpy to read the h5ad directly.

**Comment by FADHLyemen** [comment]
use library(sceasy) for conversion,
