### ISSUE TITLE
Gene names in UMAP/tSNE, dotplot, trackplot are sometimes swapped

### ISSUE THREAD

**Issue by yyoshiaki** [interactivereport/cellxgene_VIP#50]
Hi, thank you for developing a nice tool.
I noticed that gene names in VIP are often swapped.

For example, in the [example page](https://cellxgenevip-ms.bxgenomics.com/), AQP4 expression in the native cellxgene is different from the scatter plot in VIP.
![image](https://user-images.githubusercontent.com/19543497/119249180-7aef6380-bbd1-11eb-8065-1cf6d815c719.png)

**Comment by interactivereport** [comment]
Thank you for reporting. The bug was introduced few weeks ago when a new function was added in April 21. It is fixed. Please downloaded the latest version.

**Comment by yyoshiaki** [comment]
Thank you! I confirmed it worked well!
