### ISSUE TITLE
DEG Welch's t-test (cellxgene) produces rows without gene names and mostly 0 for other columns 

### ISSUE THREAD

**Issue by modash** [interactivereport/cellxgene_VIP#51]
In DEG under VIP, when I select "All" in "Select the number of top DEG", number of genes are reported correctly is equal to number of cells in the dataset. For eg, if there are 4500 cells, then I am getting 4500 genes with proper values and gene names. All other rows doesn't have gene names (empty) and other values are mostly 0, with few exceptions. Whereas, for datasets with with number of cells are more than total number of genes in the object then it works fine. For eg, if the cell count is 30,000 and number of genes are 25,000, then the results are fine. **I have updated to the latest version, still the problem persists.**

Here is the input page,
![image](https://user-images.githubusercontent.com/8167617/119707260-94fe9f80-be78-11eb-8b15-0851599c5ce5.png)

and here is the output,
![image](https://user-images.githubusercontent.com/8167617/119707302-a2b42500-be78-11eb-9e8c-9769f7ed040c.png)

Cheers,
Ashick

**Comment by modash** [comment]
After few troubleshooting, I have found the root cause of the problem. I thought of sharing here as  it might be useful for anyone facing the same problem.

In the python script, "VIPInterface.py" in cellxgene_VIP folder, in line number 695 instead of total gene count, total cell count is being used. Author is extracting the shape of the object and then uses the 0th index which is total cell count, whereas 1st index (data.shape[1]) has the total gene count. Once I changed this, it work's perfectly fine. Checked the result with diffxpy method as well, all good.

**Comment by interactivereport** [comment]
modash,
Thank you for pointing to the bug. However, I can't replicate the behavior in our demo data set. Is it related to how h5ad file is prepared? Could you please download the latest version and test again on your data set?

**Comment by baohongz** [comment]
modash,
Thank you for pointing to the bug. However, I can't replicate the behavior in our demo data set. Is it related to how h5ad file is prepared? Could you please download the latest version and test again on your data set?

**Comment by modash** [comment]
Hi, I have used the latest version. I have tried with the sample pbmc.h5ad data, there is no problem there. Because the number of genes in there is ~1.8K genes < the total number of cells in it. So all the genes are reported correctly. You can try with a dataset where number of genes are more than the number of cells. Or subset pbmc data to 1000 cells and you can try. I have used Seurat pipeline and then used sceasy to convert the RDS to H5AD. Once I fixed the array index bug, it is working perfectly fine for me.

**Comment by z5ouyang** [comment]
@modash, thanks for the report, and you are correct of the number of DEGs should be using ```shape[1]```
And a newer version updated this.
