### ISSUE TITLE
why two VIP versions give different number of cells in violin plot?

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#53]
Hi, 
I test two version of cellxgene and I get two different number of cells.
I am 100% sure that is the same object and same cell selection. 
could you help me on how to troubleshoot?

![image](https://user-images.githubusercontent.com/23288387/122827651-9e7dfa80-d2b2-11eb-8e8c-c08678678ef5.png)

**Comment by FADHLyemen** [comment]
![image](https://user-images.githubusercontent.com/23288387/122928446-e135e600-d337-11eb-8198-da099f371db5.png)

scanpy generate same violin as the old version. May be the problem is with the scaling in the new version?
any thought?

**Comment by baohongz** [comment]
Could you please check this option, "Scale data to unit ... ..."?
<img width="478" alt="Screen Shot 2021-06-22 at 9 14 02 AM" src="https://user-images.githubusercontent.com/15882624/122930948-6b7f4980-d33a-11eb-9bae-79d25ffef5d0.png">

**Comment by FADHLyemen** [comment]
Yes, I got the same violin plot when I set to no. could you tell me what is this?

**Comment by z5ouyang** [comment]
The "Scale data to unit variance for plotting: Yes", apply this to the data:
https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.scale.html#scanpy.pp.scale

If you have additional question related to "scale", please contact the "scanpy group" or your bioinformatician group.
