### ISSUE TITLE
how to use spatial transcriptomics new VIP option 

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#54]
Hi, 
I saw you have new option to use spatial transcriptomics, how to use, do you have one example, what I need beside the h5ad object?

Thank you

**Comment by FADHLyemen** [comment]
@baohongz I am interested to use the VIP for spatial transcriptomics, do you have an example how to do it?
do we need to add the image x and y to the h5ad, file?

I appreciate it.

**Comment by FADHLyemen** [comment]
@baohongz any chance you look for this question? is this option available or not yet to test?

**Comment by interactivereport** [comment]
Yes. I am writing the tutorial now. It will be ready next week.

**Comment by FADHLyemen** [comment]
Hi @interactivereport, 
Just to check in, very appreciated!

**Comment by interactivereport** [comment]
Please follow this example to generate h5ad file for your data,

https://github.com/interactivereport/cellxgene_VIP/blob/master/notebook/spatial_transcriptomics.ipynb

You could merge data from multiple slices together. After that, you can spin off an instance like regular h5ad file.

From GUI, you can then overlay images to spatial layout.

**Comment by interactivereport** [comment]
https://interactivereport.github.io/cellxgene_VIP/tutorial/docs/how-to-use-cellxgene-vip.html#vip---spatial-transcriptomics

**Comment by FADHLyemen** [comment]
could you give me an example of how to put spatial transcriptomic in the h5ad object?
If you have a real example.

**Comment by interactivereport** [comment]
Please read spatial transcriptomics related portions in the new preprint.

https://www.biorxiv.org/content/10.1101/2020.08.28.270652v2.full

And follow this notebook to prepare the h5ad file.
https://github.com/interactivereport/cellxgene_VIP/blob/master/notebook/spatial_transcriptomics.ipynb
