### ISSUE TITLE
Adapt VIP to CellxGene Ver 0.17.0

### ISSUE THREAD

**Issue by wariobrega** [interactivereport/cellxgene_VIP#55]
as per the title request, I gave tried to adapt the code to version 0.17 but the backend server directory tree dramatically changed and I have several errors. 

Can you make a version compatible with the new cellxgene? 

Thanks in advance!

**Comment by michaeleekk** [comment]
I think I got this extension worked with 1.0.0 in https://github.com/interactivereport/cellxgene_VIP/issues/62.

Hope it helps :)

**Comment by z5ouyang** [comment]
If you run "config.sh" again in your conda env. will be using cellxgene v1.1.1
