### ISSUE TITLE
Integrating cellxgene_VIP and cellxgene-gateway

### ISSUE THREAD

**Issue by PolinaPavlovich** [interactivereport/cellxgene_VIP#56]
Hello,

Thank you for the amazing software. Is there any way to combine cellxgene_VIP and cellxgene-gateway?

Best regards,
Polina

**Comment by z5ouyang** [comment]
@PolinaPavlovich,
Thanks for the interests.
If the reason of using the "cellxgene-gateway" is to host multi-datasets, now the cellxgene itself provided "cellxgene launch --dataroot ..." by providing the path to a folder where hold multiple h5ad files.
And then using "http://.../d/XXXXX.h5ad/" to access the specific h5ad named XXXXX.h5ad.

Hope this helps, please reopen this if you are looking for something else.

**Comment by Jon-bioinfo** [comment]
cellxgene-gateway and VIP are working together nicely for me if you point cellxgene-gateway to the version of cellxgene modified by VIP. Allowing the browsing of a list of datasets, then opening several with VIP active in each cellxgene tab.

I set it up like this:
```
git clone https://github.com/interactivereport/cellxgene_VIP.git
cd cellxgene_VIP
source ~/mambaforge/etc/profile.d/conda.sh 
conda config --set channel_priority flexible
mamba env create -n VIP -f VIP_conda_R.yml 
conda activate VIP
./config.sh
mamba install -c bioconda r-devtools r-seurat==3.2.3 bioconductor-fgsea r-rmarkdown r-tidyverse r-viridis r-arrow r-cairo r-foreign r-ggpubr r-ggrastr
pip install cellxgene-gateway

export CELLXGENE_LOCATION=~/mambaforge/envs/VIP/bin/cellxgene
export CELLXGENE_DATA=/data/cellxgene_data
cellxgene-gateway
```
mamba/conda can be swiched.
I also like using the local R inside the conda environment and using conda/mamba install. So much faster.
