### ISSUE TITLE
No VIP on the chrome site?

### ISSUE THREAD

**Issue by SimoniMD** [interactivereport/cellxgene_VIP#57]
Hi,

I'm trying to use cellxgene VIP and unable to see any of the plugins. I've tried both with my dataset and a test dataset. The cluster pops up, but none of the plugins (or the pull-down bar for that matter) appear. I've tried using a conda3 and a miniconda environment...the error i get in the console a bunch of stuff that looks like this:

<img width="527" alt="Screen Shot 2021-08-30 at 1 53 13 PM" src="https://user-images.githubusercontent.com/82599359/131382894-a319e4a3-e1b1-4a99-9751-6cbd92fc5cdd.png">

Is this a connection error on my end?

**Comment by z5ouyang** [comment]
This seems like the nodejs was not installed/configured successfully.
A couple of questions: 
1. the chrome version
2. did you installed VIP only? or you installed cellxgene directly after?

**Comment by z5ouyang** [comment]
needs mac install as #44.
After install the mac version, it was successfully.
