### ISSUE TITLE
how to download selected cells?

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#58]
Hi, I want to download selected cells, not in the red circle? is there a way to do it in cellxgene VIP?

![image](https://user-images.githubusercontent.com/23288387/132061273-7eca22a6-6503-4789-bba0-3b4f5accf474.png)

**Comment by z5ouyang** [comment]
@FADHLyemen, if the "download selected cells" mean the cell (name/ID), you can select the cells first, and many plot provide "Data" download, such as heatmap, it will contains cell IDs/Names.
If this is not the answer you are looking for, please reopen and explain.
Thanks!
