### ISSUE TITLE
Expression Cutoff discondorance for Subgrouped Violin Plots

### ISSUE THREAD

**Issue by SimoniMD** [interactivereport/cellxgene_VIP#61]
Hi, 

With the subgrouped violin plots, there is no way to change the expression cutoff so that it calculates the expression means with the cells it does not filter (if cells are 0 or less than 0). This creates a disconcordance with the dotplots. Please add this feature =).
![SGVcompareimg (29)](https://user-images.githubusercontent.com/82599359/139563434-a287dcba-0eb1-4770-8856-afdb578ef898.png)

![DOTimg (23)](https://user-images.githubusercontent.com/82599359/139563436-83cd956f-d98d-4a48-b205-699d9f7f4e4b.png)

**Comment by z5ouyang** [comment]
Please pull the new version, and activating your env before executing ```./update.VIPInterface.sh``` . You can select the cell filtering on violin page:
![image](https://user-images.githubusercontent.com/30639029/139567908-c741a47e-e850-4444-bb68-7352db6e6bbf.png)
