### ISSUE TITLE
Cairo R package installation

### ISSUE THREAD

**Issue by wanliw96** [interactivereport/cellxgene_VIP#68]
Hi,

I was trying to install R package Cairo using
R -q -e 'if(!require(Cairo)) devtools::install_version("Cairo",version="1.5-12",repos = "http://cran.us.r-project.org")'

And I get this error message:

configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set ### **CAIRO_CFLAGS/LIBS** correspondingly.
ERROR: configuration failed for package ‘Cairo’

Maybe any system installation is needed before this?

Thanks!

**Comment by haessar** [comment]
If you are on Debian/Ubuntu, try running:
_sudo apt install libcairo2-dev_
beforehand.
