### ISSUE TITLE
ggrastr & viridis R Packages Not Found

### ISSUE THREAD

**Issue by trentleslie** [interactivereport/cellxgene_VIP#69]
Hi,

We are running a cellxgeneVIP instance on AWS, and I am having a couple issues when trying to generate volcano plots in VIP DEG and trying to generate density scatter plots in VIP Density Scatter.

In DEG, the error returned:

```
ERROR @server: Traceback (most recent call last):
  File "/home/*****/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 57, in route
    taskRes = distributeTask(data["method"])(data)
  File "/home/*****/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 731, in DEG
    raise SyntaxError("in volcano.R: "+res.stderr.decode('utf-8'))
  File "<string>", line None
SyntaxError: in volcano.R: Error in library(ggrastr) : there is no package called ‘ggrastr’
Execution halted
```

In Density Scatter, the error returned:

```
ERROR @server: Traceback (most recent call last):
  File "/home/*****/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 57, in route
    taskRes = distributeTask(data["method"])(data)
  File "/home/*****/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 1193, in DENS2D
    raise SyntaxError("in R: "+res.stderr.decode('utf-8'))
  File "<string>", line None
SyntaxError: in R: Error in loadNamespace(x) : there is no package called ‘viridis’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

And a screenshot of the DEG issue:

![image](https://user-images.githubusercontent.com/1095657/155008263-600ee18e-11bd-4c6b-88c0-deee214f164a.png)

It looks like a similar issue mentioned [here](https://github.com/interactivereport/cellxgene_VIP/issues/42), but there's no information about a solution there. Any suggestions on how to install/identify the packages needed? Thanks for any help!

Cheers,
Trent

**Comment by baohongz** [comment]
Please follow this,

https://github.com/interactivereport/cellxgene_VIP#4-install-r-packages

If you don't have admin right, please use VIP_conda_R.yml at step 2.

**Comment by trentleslie** [comment]
Got it, I was using someone else's existing VIP install but didn't realize I needed to configure my own R environment on my end. Packages were installed using Step 4 and all is good, thank you for the quick response!
