### ISSUE TITLE
Error in installation of .yml file

### ISSUE THREAD

**Issue by williestyle925** [interactivereport/cellxgene_VIP#75]
Hi, thank you for the great work!

After trying a few hours to solve the installation problems, I still face errors while running the conda environment from VIP_conda_R.yml.

Solving environment: failed
ResolvePackageNotFound:
....

I then put the required functions under --pip, and the package conflict of several package showed up.

Would anyone face the same issues and how to deal with this error?  Many thanks to your reply!

**Comment by likejie** [comment]
Sorry for the delayed reply! 

conda solver could be very slow. Please try the following by using mamba:
```
conda install -c conda-forge mamba
conda create -n <your envname>
mamba env update -n <your envname> -f VIP_conda_R.yml
conda activate <your envname>
```

This should be much faster.

Please let me know. Thanks!

**Comment by z5ouyang** [comment]
Please checkout new one step installation: install_VIPlight.sh (linux) install_VIPlight.macOS.sh (mac OS).
