### ISSUE TITLE
Plugins are not available for the new cellxgene version 1.0.1

### ISSUE THREAD

**Issue by pkhoueiry** [interactivereport/cellxgene_VIP#77]
@z5ouyang Upon upgrading cellxgene to version 1.0.1, the plugins are not available anymore!

**Comment by JialiUMassWengLab** [comment]
I have the same issue. After installation there's a prompt to update to version 1.0.1 with pip install. After that the VIP panel disappeared. @interactivereport @z5ouyang any suggestions please?

**Comment by JialiUMassWengLab** [comment]
After communicating with the developers, version 1.0.1 is not ready yet. So users should refrain from upgrading to v1.0.1 for now. Additionally it is advisable to use the Scanpy contained within the VIP virtual environment to generate the .h5ad files. I used a later version (v1.9.1) and cellxgene won't recognize the .h5ad file generated that way.

**Comment by pkhoueiry** [comment]
Thanks for the update @JialiUMassWengLab .

**Comment by Dane-Z** [comment]
Same issue

**Comment by tjneu** [comment]
Some datasets fail to launch on cellxgene-VIP using s3 urls as well. Although it has to with cellxgene version 0.16.8 and not VIP per se, but this issue has been fixed with cellxgene version >=1.0.1, so I'm curious if there are any plans to update VIP

**Comment by z5ouyang** [comment]
If you run "config.sh" again in your conda env. will be using cellxgene v1.1.1
