### ISSUE TITLE
Issue running cellxgene_VIP

### ISSUE THREAD

**Issue by curtisd0886** [interactivereport/cellxgene_VIP#83]
Hello,
I am trying to get cellxgene_VIP running, but keep running into an issue at startup. If I run standard CellXgene through a PIP install I have no issues, but if I follow the CellxGene_VIP installation instructions and try to run I get the following error:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/VIP/bin/cellxgene", line 5, in <module>
    from server.cli.cli import cli
  File "/opt/anaconda3/envs/VIP/lib/python3.8/site-packages/server/cli/cli.py", line 4, in <module>
    from .launch import launch
  File "/opt/anaconda3/envs/VIP/lib/python3.8/site-packages/server/cli/launch.py", line 12, in <module>
    from server.app.app import Server
  File "/opt/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/app.py", line 461, in <module>
    from server.app.VIPInterface import route
  File "/opt/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 38, in <module>
    import server.common.compute.diffexp_generic as diffDefault
ModuleNotFoundError: No module named 'server.common.compute'

Any Idea what could be causing this? As far as I can tell there were no errors during the installation process. Thanks for your help.

**Comment by alexlenail** [comment]
+1 same issue

**Comment by alexlenail** [comment]
It's this line: 

https://github.com/interactivereport/cellxgene_VIP/blob/f449f2e018622a87fc9bb208e2c7b9aad668a6fe/VIPInterface.py#L38

Trying to import this module:

https://github.com/chanzuckerberg/cellxgene/blob/main/server/common/compute/diffexp_generic.py

suggesting cellxgene is not installed, or getting being clobbered by something else

**Comment by z5ouyang** [comment]
@curtisd0886 & @alexlenail Is this the new installation with cellxgene v1.1.1? I did a fresh install without any issues.

**Comment by z5ouyang** [comment]
cellxgene v1 did a major change from previous version of how their methods could be called. Please reinstall/update the VIP accordingly if you would like to use cellxgene V1.
Thanks!
Please reopen if the issue still exists.
