### ISSUE TITLE
RNA information in multiomic visualization

### ISSUE THREAD

**Issue by shengyongniu** [interactivereport/cellxgene_VIP#87]
Hi cellxgeneVIP team, thank you for the detailed tutorial about how to generate input for single-cell multi-omic for celxgeneVIP. After testing the dataset following your tutorial, it seems that although there's no problem visualizing the ATAC part, the transcriptome information is not included. I cannot add any genes or plot anything about gene expression. Do you have any suggestions for revising the codes in your tutorial? https://github.com/interactivereport/cellxgene_VIP/blob/50a091f62c895f967999e023ce612e3b8ff2713c/notebook/pbmc_multiome.md  

Thank you!

**Comment by interactivereport** [comment]
Did you also generate the h5ad file, which holds gene expression values? Please check the end of the tutorial for files needed.
https://github.com/interactivereport/cellxgene_VIP/blob/50a091f62c895f967999e023ce612e3b8ff2713c/notebook/pbmc_multiome.md

**Comment by shengyongniu** [comment]
Yes, I also generated the h5ad file. I follow everything in the tutorial including the end of it. It seems it can’t retrieve RNA information even with your example dataset. 
just to confirm, the h5ad file is outside of the folder that contain bigwig files, correct?

**Comment by z5ouyang** [comment]
@shengyongniu, Thanks for the report. I just tested, and the gene violin shows up. One note: you have to add genes through either using "Add Genes" first left tab, or "Genes" on the top right cornor of cellxgene page. Those added genes will then shows in the "Multiome" page, listed under "Add following gene expression violins to tracks ('Add Genes' first)". 
Please let me know if this works.
![image](https://user-images.githubusercontent.com/30639029/213539730-e00c54e8-2fac-4fc0-ac86-204d6ddb4538.png)

**Comment by shengyongniu** [comment]
@z5ouyang I figured out that the reason I couldn't select the genes was that I needed to specify RNA assay during the conversion to h5ad; otherwise, it will only convert the ATAC part, not the RNA part by default.
About the violin plot in the multiome tab, it still doesn't show up on my side. Does it require a certain version of cellxgene to do it? Thanks!

**Comment by z5ouyang** [comment]
@shengyongniu, I don't think it is an issue with cellxgene version. We did an update recently to specify the bw.cluster (as a table) to be shown on the interface. bw.cluster file (in the folder along with bw files) is a table (separated by \t tab):
1. First column header has to be “Wig"
2. Column header can include more than one annotations or/and other meta information;
3. If an annotation was used in the header, the entry will be used to find the cells
4. If a bw row contains more than one annotation columns, the intersect will be used to find the cells
5. If an annotation entry is empty string(""), it will be ignored, other annotation entries will be used to find the cells
Hope this helps!

Please reopen if this didn't solve your issue. Thanks
