### ISSUE TITLE
DEG not working!!!

### ISSUE THREAD

**Issue by AAlhendi1707** [interactivereport/cellxgene_VIP#88]
Hi @z5ouyang

I wanted to take a moment to express my appreciation for all the fantastic visualization plugins you have put together. They have been incredibly helpful!.

However, I have been experiencing some difficulty with the DEG visualization plugin in the current version of CellxGene VIP v 1.1.1. Despite trying different methods, selecting different cells, and even different scRNA datasets, I have not been able to get any results. After the run is complete, the plot is blank (as shown in the attached screenshot).

I was wondering if you had any suggestions on how I can resolve this issue. Any assistance would be greatly appreciated.

Thank you for your time and help. 
![image](https://user-images.githubusercontent.com/44529285/220145040-4bc5e1c5-a7c0-4be5-bb31-c924bd00a73d.png)

**Comment by z5ouyang** [comment]
@AAlhendi1707 , thanks for using the cellxgene VIP and sharing the issue. It was a bug, and fixed by c44a899. Please pull and execute "./update.VIPInterface.sh" after activating your env.

Please reopen this if it didn't fix your issue! Thanks!
