### ISSUE TITLE
PackagesNotFoundError yip.vml

### ISSUE THREAD

**Issue by dfermin** [interactivereport/cellxgene_VIP#90]
Hello

I'm trying to perform a fresh install of Cellxgene_VIP. 
After downloading the repo from github I enter the cellxgene_VIP directory and type:

```
conda create -n VIP -f VIP.yml
```

I get the following error:
```
PackagesNotFoundError: The following packages are not available from current channels:

- vip.yml
```

I've not seen this error before. It seems conda is interpreting the YAML file name like a package. 
Is there a work around for this?
I'm using conda version 23.1.0 on a RHEL 8.0 system. 

Thanks

**Comment by z5ouyang** [comment]
If you don't use CLT tab/tools, I recommend you use "VIPlight.yml" which is a lighter recently tested installation which included the needed R env with packages.
Please let me know if this helps.
