### ISSUE TITLE
Problems with gene names

### ISSUE THREAD

**Issue by Edhelia** [interactivereport/cellxgene_VIP#91]
Hi :)
I used Cellxgene VIP, it's great thx all:)
But I 've a little problems, the names of the genes do not appear, I have to indicate the Ensembl numbers. If I indicate names generic (for exemple STAT5A), it does not work I have to indicate ENSG000.... 

The h5ad file I'm using is on my computer, downloading directly from the server. It works perfectly with cellxgene (the name of the genes is present), but as soon as I launch cellxgen-VIP I have to enter the numbers Ensembl to find my genes.. which is very problematic for me..
Do you have any idea why this is not working?

thank you very much for your time

PS: excuse my English :p

**Comment by z5ouyang** [comment]
Could you provide the version of the anndata. VIP currently only support anndata <0.8. And if you load your data, adata.var_name is used as gene identifier in the cellxgene and cellxgeneVIP. Please let me know if this helps.

**Comment by Edhelia** [comment]
It's work, I just add --var-names feature_name 

thx :)
