### ISSUE TITLE
DEG list

### ISSUE THREAD

**Issue by Niahmd** [interactivereport/cellxgene_VIP#92]
Hi,

I can't see the plot for DEG in cellxgeneVIP and can't even extract the gene list.
Is there anyway I can export the DEG list from cellxgeneVIP?

**Comment by z5ouyang** [comment]
You can save the DEG list from cellxgeneVIP.
could you please provide a little more information? Like which OS? setup using conda R or system R? A screen shot of DEG tab would also helpful.

**Comment by z5ouyang** [comment]
Closing since lacking more information. Please reopen, if needed.
