### ISSUE TITLE
cellxgene_VIP install problem -- macos

### ISSUE THREAD

**Issue by theDierickxLab** [interactivereport/cellxgene_VIP#93]
Hi

My system is macOS Monterey 12.6.7.

To install VIP, I did the following steps:
git clone https://github.com/interactivereport/cellxgene_VIP.git
cd cellxgene_VIP

source <path to Anaconda3>/etc/profile.d/conda.sh 
conda config --set channel_priority flexible
conda env create -n VIP  -f VIP.macOS.yml. (I have an error in this step. I changed the **flask to 1.1.2**)
conda activate  VIP
./config.macOS.sh
export LIBARROW_MINIMAL=false
R packages install
ps -ef | grep cellxgene
Rscript -e 'reticulate::py_config()'
export RETICULATE_PYTHON=`which python`
cellxgene launch --host localhost--port 5007 --disable-annotations --verbose <h5ad file>
(But I have error **ModuleNotFoundError: No module named 'server.common.compute'**)
So then I did:
./update.VIPInterface.sh all
./update.index_template.sh
Then I still have the problem.
![image](https://github.com/interactivereport/cellxgene_VIP/assets/114193939/ebe1f218-a3ff-43a0-880b-d380d0e09d51)
Then I tried to update cellxgene: pip install --upgrade cellxgene
Then VIP disappeared. 

Could you help me check the problem? Thanks in advance!!

**Comment by theDierickxLab** [comment]
Hi,

I solved the problem by updating the cellxgene version and VIPInterface.sh. The config.macOS.sh should be updated. 

Thanks a lot.

Best wishes,
Kai

**Comment by interactivereport** [comment]
Kai,

Thank you! Could you please post your whole solution here, so I can incorporate into the  repo?

Best,
Baohong

**Comment by pdichiaro** [comment]
Hi all,
the suggestion doesn't work for me . 
After  **cellxgene launch --host xxx--port xxx --disable-annotations --verbose file.h5ad**
![Screenshot 2023-10-20 at 11 59 44](https://github.com/interactivereport/cellxgene_VIP/assets/50377927/910588b8-4c77-4227-8774-e822ef2e0c20)

**Comment by mariaUCL** [comment]
I am also now getting this error. Have you resolved it?

**Comment by z5ouyang** [comment]
Please check the 86aabcad9d69c7d536a3d97bfad31b693fac8c6c including a ONE STEP VIPlight installation for for macOS: install_VIPlight.macOS.sh (tested on M2 Ventura). Please reopen the issue, if encountering problems. Thanks for your interests!
