### ISSUE TITLE
Issues with installing R packages 

### ISSUE THREAD

**Issue by TimothyTse001** [interactivereport/cellxgene_VIP#94]
To whom it may concern, 

I'm having problems with installing R packages after installing cellxgene. I manage to perform all of the steps until step 3 but when I pasted the code for eg. R -q -e 'if(!require(devtools)) install.packages("devtools",repos = "http://cran.us.r-project.org")'.....it tells me that 
"there is no package called devtools" "execution halted". Could you please help me resolve my problem? Thanks!

**Comment by likejie** [comment]
You will need to install devtools package first. Make sure you have the permission to install R packages.
The following line of command in the terminal would install devtools for you.

R -q -e 'if(!require(devtools)) install.packages("devtools",repos = "http://cran.us.r-project.org")'

If you are using conda env R, you could install r-devtools from conda:

conda install -c conda-forge r-devtools

Hope this helps.

**Comment by TimothyTse001** [comment]
Hey, 

Many thanks for the reply! I've tried installing using the command "conda install -c conda-forge r-devtools" but there is an issue with the conda solver. It is stuck in a loop with "collecting package metadata (repodata.json)" and it is not progressing. Is there a way to resolve this? Many thanks!
