### ISSUE TITLE
customized pathway database

### ISSUE THREAD

**Issue by lindongdo** [interactivereport/cellxgene_VIP#97]
Dear developers,
I was looking for a way to import customized pathway database (e..g, gmt file) for geneset visualization and gsea analysis. Do you have any suggestions?
Also, the new version of cellxgene provides some cool functions for geneset visualization, will cellxgene vip be able to sync those geneset info with cellxgene as well?

Thanks!
Dongdong

**Comment by z5ouyang** [comment]
Yes, you can download/prepare GMT files, and put them into the "gsea" folder, and run ./update.VIPInterface.sh, all those GMT files will be copied into the VIP and you will be able to see them in your next VIP lanuch.
